### ISSUE TITLE
Add a link to container image analyses in Thoth Search UI

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#1080]
**Is your feature request related to a problem? Please describe.**

As a user of Thoth, I would like to browse results of container image analyses in Thoth search by visiting a link shown when running `thamos images`.

**Describe the solution you'd like**

Thamos should show a link to Thoth Search UI with more details about the container image analyses.

**Comment by codificat** [comment]
based on activivity:
/triage accepted
/lifecycle active
/assign @mayaCostantini
/priority important-soon

It's unclear to me if this was already addressed by #1083. Feel free to close if so

**Comment by mayaCostantini** [comment]
Closed by https://github.com/thoth-station/thamos/pull/1083
