### ISSUE TITLE
justifications use thoth-search as part of the url

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#1082]
**Describe the bug**
`/thoth-search` is used rather than `/search`

```
$ thamos version
Thamos Client version: 1.27.2
Thoth API https://khemenu.thoth-station.ninja/api/v1: 0.34.10
```

**To Reproduce**
1. follow the 

**Expected behavior**
use  `/search`

/priority critical-urgent
/assign @fridex 
/traige accepted

**Comment by fridex** [comment]
This has been already fixed in https://github.com/thoth-station/adviser/pull/2296 and will be part of the next release of adviser to prod (stage should be fine). We plan to release adviser outside of the sprint cycle soon.
