### ISSUE TITLE
[2pt] thamos vs thoth as package name

### ISSUE THREAD

**Issue by ssbarnea** [thoth-station/thamos#1103]
To be honest I find quite confusing to differentiate between `thoth` and `thamos` as names. Both names start with `th`, making even harder to guess which on is which.

My first experience was to attempt to do `pip install thoth` which rendered into an installation failure.

After trying `pip install thamos`, i got it installed but first line of output adds to the confusion
```
$ thamos           
                                                                                                                                                                
 Thoth homepage: https://thoth-station.ninja          
```

I see a bit of "branding" issue here. Not sure what should be done but it worth mentioning, especially as these kind of changes become harder once a product become more mature.

**Comment by fridex** [comment]
Thanks for the report @ssbarnea. :+1:

We own `thoth` package (it was created as a placeholder initially). The concern raised seems valid to me and I'm wondering what we could do to improve the situation. Would it make sense to adjust the error message reported when performing `pip install thoth` and refer to thamos instead?

**Comment by ssbarnea** [comment]
A hint: if you own both package names on pypi.org, you can ask them to make one alias to another. I used this once or twice.

Regarding spelling, I am not sure what to say. I find both bit hard to remember or pronounce, but English is not my native language either. Get feedback from others, don't react only on mine. Maybe someone will come with a brilliant idea.

**Comment by fridex** [comment]
> A hint: if you own both package names on pypi.org, you can ask them to make one alias to another. I used this once or twice.

That's cool. Where should we reach out to? Is [PyPI's issue tracker](https://github.com/pypa/pypi-support) the right place for this?

> Regarding spelling, I am not sure what to say. I find both bit hard to remember or pronounce, but English is not my native language either. Get feedback from others, don't react only on mine. Maybe someone will come with a brilliant idea.

Yes, sometimes it is also funny to hear various pronunciations :) I was thinking to make thoth an alias to thamos on the command line (which might make even more confusion maybe?). But I agree the naming is not perfect on our side.

**Comment by fridex** [comment]
> A hint: if you own both package names on pypi.org, you can ask them to make one alias to another. I used this once or twice.

That's cool. Where should we reach out to? Is [PyPI's issue tracker](https://github.com/pypa/pypi-support) the right place for this?

> Regarding spelling, I am not sure what to say. I find both bit hard to remember or pronounce, but English is not my native language either. Get feedback from others, don't react only on mine. Maybe someone will come with a brilliant idea.

Yes, sometimes it is also funny to hear various pronunciations :) I was thinking to make thoth an alias to thamos on the command line (which might make even more confusion maybe?). But I agree the naming is not perfect on our side.

**Comment by Gkrumbach07** [comment]
A new description was added to the thoth pypi page that links to thamos.
