### ISSUE TITLE
Thoth container image name and version are not provided in `thamos images` command

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thamos#1106]
## Bug description
When running `thamos images` with `thamos v1.27.5`, Thoth container images name and version are not printed in the command output. After verification, those values are `None` for all container images listed.

### Steps to Reproduce
Upgrade thamos if necessary and run `thamos images`.

### Expected behavior
Container images name and version are found and displayed in the output of the command.

### Additional context
![Screenshot from 2022-04-13 14-49-19](https://user-images.githubusercontent.com/66788861/163184143-1f961ec1-60be-4520-afbf-9ca74a7bd42a.png)

**Comment by fridex** [comment]
> Thanks @fridex it would be great 100

See https://github.com/thoth-station/thoth-application/issues/1788 This information is reused.
