### ISSUE TITLE
[1pt] Document fields of the advise report in JSON format

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thamos#1116]
## Problem statement

As a user of Thamos, I would like to have access to a document describing the different fields present in the advise report in JSON format and the structure of the report.

## Proposal description
 - [ ] Document the JSON advise report fields in this repository
 - [ ] Eventually make a link to this documentation accessible via a thamos command

**Comment by fridex** [comment]
This JSON documentation should be also [browsable and "clickable" directly on the deployed service](https://khemenu.thoth-station.ninja/api/v1/ui/#/Advise/get_advise_python).

**Comment by fridex** [comment]
This is more technical documentation, suitable for devs rather than users. But if you find it useful, you can link it.

**Comment by mayaCostantini** [comment]
Right, in this case I think documenting this in the readme would be enough, no need to overload a thamos command. Thanks! :100:
