### ISSUE TITLE
Modify `_parse_labels` logic to allow specifying a list of values

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thamos#1120]
## Bug description

The [logic](https://github.com/thoth-station/thamos/blob/78bd6d6606c99801b3766e1f579db945e9eb4c7e/thamos/cli.py#L211) to parse `--labels` should take into account having a list of values specified for a same label key, as in `--labels allow-cve=PYSEC-2021-94,PYSEC-2021-2`.

### Steps to Reproduce

Run thamos with a list of values for a same label (see example above).

**Comment by fridex** [comment]
Is this related to some issue? Labels that are sent to the backend, in this case, should be:

```json
{
    "allow-cve": "PYSEC-2021-94,PYSEC-2021-2"
}
```

Backend understands that `allow-cve` is a comma-separated list of CVEs to allow.
