### ISSUE TITLE
Print a concise summary of Scorecard metrics when the `--scoring` flag is passed on `thamos advise`

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#1149]
In the context of https://github.com/thoth-station/core/issues/434

**_PoC: Implement an experimental thamos flag on the advise command to give users insights about the maintenance of their packages_**

**Comment by mayaCostantini** [comment]
Let's close this issue as this feature was implemented in https://github.com/thoth-station/thamos/pull/1155.
The evolution of the scoring logic can be tracked by https://github.com/thoth-station/core/issues/434.
