### ISSUE TITLE
[2pt] Provide command alias for `thamos results`

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/thamos#1151]
## Problem statement

- [ ] Provide an alternative alias `result` to the `results` command to avoid any confusion
- [ ] Add the command to the general help section

### Alternatives

Leave `results` without an alias.

**Comment by codificat** [comment]
As per #1156 I believe this is not necessary, so I suggest to
/close

Feel free to reopen/clarify as appropriate.
