### ISSUE TITLE
Introduce versions in Thoth's configuration file

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#126]
**Is your feature request related to a problem? Please describe.**

We could introduce "`version`" field in the `.thoth.yaml` file. This way we can warn a user if she/he is using old thamos library with newer configuration file.

**Describe the solution you'd like**

Introduce `version` key, we could follow `<major>.<minor>` scheme and let thamos error out on non-backwards  compatible changes in the configuration file.

**Describe alternatives you've considered**

Keep it as is.

**Comment by goern** [comment]
thamos should send its version with each request to the API, so that the API could issue a warning that could be displayed to the user by thamos

**Comment by fridex** [comment]
Or maybe just keep it as it is now, as configuration is part of API schema which is versioned already.

**Comment by fridex** [comment]
I will close this one in respect to https://github.com/thoth-station/thamos/pull/255 Feel free to reopen if this is still relevant.
