### ISSUE TITLE
Empty `report` causes IndexError

### ISSUE THREAD

**Issue by CermakM** [thoth-station/thamos#196]
If analysis returns result containing empty `report`, it causes IndexError.

```python
IndexError                                Traceback (most recent call last)
<ipython-input-92-2ee9676dc779> in <module>
     20 
     21 if not error:
---> 22     pipfile = report[0][1]["requirements"]
     23     pipfile_lock = report[0][1]["requirements_locked"]
     24 else:

IndexError: list index out of range
```

Perhaps this case should be handled more appropriately?

**Comment by fridex** [comment]
I wonder when this can occur. Probably when analysis gets OOM killed or CPU time gets exhausted, the stack producer is killed and it does not produce any stacks until that time.

It might be good to report an error in that case (so we enter the error handling branch) as we did not come up with any results. This will require a fix in adviser.

**Comment by CermakM** [comment]
Yup, there is a bit of work with respect to the OOM handling I guess, a few more issues are related to that as well.
