### ISSUE TITLE
Create the pipfile.lock locally if the thoth-station backend has errors

### ISSUE THREAD

**Issue by 4n4nd** [thoth-station/thamos#261]
I build my application images on openshift using the `quay.io/thoth-station/s2i-thoth-ubi8-py36:latest` image and when thamos cannot connect to the thoth-station backend, the build fails.

There could be a fallback option for the container image when connection to the backend fails, it could lock the dependencies locally.

**Comment by fridex** [comment]
@4n4nd I think this is more related to https://github.com/thoth-station/s2i-thoth. To my understanding, you are building a container image in an OpenShift cluster which is based on s2i-thoth-ubi-py36 and the build fails as the Thoth service can be unreachable/not responsive.

**Comment by fridex** [comment]
@4n4nd PTAL at https://github.com/thoth-station/s2i-thoth/pull/21

**Comment by goern** [comment]
I have released the latest s2i-thoth to https://quay.io/repository/thoth-station/s2i-thoth-fedora30-py37?tab=tags and https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py36?tab=tags as `:latest` and `:v0.3.0`
