### ISSUE TITLE
Thamos advise fails. 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/thamos#340]
Thamos advise fails on running with a 'Failed to establish pod watch' error. 
The repo on which thamos advise was run - https://github.com/saisankargochhayat/thamos_test/blob/master/.thoth.yaml
Pod logs - 
[pod.log](https://github.com/thoth-station/thamos/files/4256528/pod.log)

**Comment by fridex** [comment]
Please submit the error so that we keep track of it (pods/logs will be deleted after some time).
