### ISSUE TITLE
Released version is not updated in PyPI

### ISSUE THREAD

**Issue by harshad16** [thoth-station/thamos#375]
**Describe the bug**
Previous released version v0.9.2 is not the latest in Pypi https://pypi.org/project/thamos/

**To Reproduce**
1. Compare https://pypi.org/project/thamos/ and https://github.com/thoth-station/thamos/blob/5f9239708a889fb2c2cd1416ed826f47047903fe/thamos/__init__.py#L21

**Expected behavior**
The application version released and latest version on pypi must be in sync.

**Comment by fridex** [comment]
I've released it manually. There was an issue with setup.py so the release pipeline failed - fix in 35962e288d2a9187d Feel free to reopen if the issue persists.
