### ISSUE TITLE
Parse and use thoth's config file on thamos library side [5pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#384]
**Is your feature request related to a problem? Please describe.**
In order to improve the user experience, parse and use thoth's config file on thamos library side.
**Describe the solution you'd like**
Moving logic from https://github.com/thoth-station/Qeb-Hwt/blob/master/workflows/templates/thamos-advise-template.yaml to thamos, not to force users to load, parse thoth's configuration file.

**Additional context**
Reference: https://github.com/thoth-station/Qeb-Hwt/pull/35#pullrequestreview-390073975

**Comment by fridex** [comment]
The description seems to be misleading - we alrady provide `thamos config` that creates a default configuration for you.

My comment was to parse and use thoth's config file on thamos library side, not to force users to load, parse thoth's configuration file - that might change over time.

**Comment by pacospace** [comment]
> The description seems to be misleading - we alrady provide `thamos config` that creates a default configuration for you.
> 
> My comment was to parse and use thoth's config file on thamos library side, not to force users to load, parse thoth's configuration file - that might change over time.

Sorry my bad, I will update that :)

**Comment by pacospace** [comment]
We can close this issue, as thoth config is manipulated using thamos library already. Thanks @fridex!

**Comment by pacospace** [comment]
See discussion in: https://github.com/thoth-station/thamos/issues/622

**Comment by fridex** [comment]
Done in #623
