### ISSUE TITLE
Introduce timeout for backend requests

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#418]
**Is your feature request related to a problem? Please describe.**

As of now, Thamos pulls for results from user-api. As Thoth backend can be overloaded or it can be experiencing issues with workflows - I, as a user, would like to have ability to specify a timeout for requests so that thamos does not wait in an endless loop.

**Describe the solution you'd like**

Introduce a timeout for requests. This timeout can be configured via an environment variable (something like ``THAMOS_TIMEOUT``) that will specify how many seconds Thamos should try obtaining results. If results cannot be retrieved, Thamos fails with an appropriate error message (so that the build process can continue on ``THOTH_ERROR_FALLBACK``)

**Additional context**

The environment variable should be documented in the README file and there should be configured some default.

https://github.com/thoth-station/thamos/blob/a4d7e3b22a0a819338334c8281e626a32d865a22/thamos/lib.py#L93

**Comment by saisankargochhayat** [comment]
@fridex from the `_wait_for_analysis` POV it will just raise an exception if the function takes longer than `THAMOS_TIMEOUT` right? The build continuing part and catching that exception would be handled elsewhere?

**Comment by fridex** [comment]
> @fridex from the `_wait_for_analysis` POV it will just raise an exception if the function takes longer than `THAMOS_TIMEOUT` right? The build continuing part and catching that exception would be handled elsewhere?

Yes, the `_wait_for_analysis` function can just raise an exception causing the Thamos CLI to exit with non-zero value.

**Comment by saisankargochhayat** [comment]
> > @fridex from the `_wait_for_analysis` POV it will just raise an exception if the function takes longer than `THAMOS_TIMEOUT` right? The build continuing part and catching that exception would be handled elsewhere?
> 
> Yes, the `_wait_for_analysis` function can just raise an exception causing the Thamos CLI to exit with non-zero value.

Do we want the retry to work after a TimeoutException, like the logic that makes thamos retry 3 times?

**Comment by fridex** [comment]
I think this can be closed given the changes made by @saisankargochhayat. Already implemented in #423.
