### ISSUE TITLE
Add an ability to manage lock files in nested directories

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#464]
**Is your feature request related to a problem? Please describe.**

Some projects maintain lock files not in a git root directory, but in some of the nested dirs present in the repo. This structure makes it harder to integrate with Thoth.

**Describe the solution you'd like**

Add an ability to maintain lock files in nested directories. The configuration file .thoth.yaml will be picked from one of the parent directories.

**Describe alternatives you've considered**

Copy .thoth.yaml file into nested directories so that the configuration is picked along with the lock file.

**Comment by fridex** [comment]
Low priority as of now.

**Comment by pacospace** [comment]
Important for: https://github.com/aicoe-aiops/project-template/issues/25
Important for: https://github.com/opendatahub-io/s2i-lab-elyra/issues/11

it would be useful for: https://github.com/thoth-station/jupyter-nbrequirements/pull/282/files

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Some projects maintain lock files not in a git root directory, but in some of the nested dirs present in the repo. This structure makes it harder to integrate with Thoth.
> 
> **Describe the solution you'd like**
> 
> Add an ability to maintain lock files in nested directories. The configuration file .thoth.yaml will be picked from one of the parent directories.
> 
> **Describe alternatives you've considered**
> 
> Copy .thoth.yaml file into nested directories so that the configuration is picked along with the lock file.

What if different steps in a pipeline requires use of different hardware (just to mention one degree of freedom for the selection of the software stack)? each software stack should be coupled with a specific .thoth.yaml. See links above.

**Comment by fridex** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > Some projects maintain lock files not in a git root directory, but in some of the nested dirs present in the repo. This structure makes it harder to integrate with Thoth.
> > **Describe the solution you'd like**
> > Add an ability to maintain lock files in nested directories. The configuration file .thoth.yaml will be picked from one of the parent directories.
> > **Describe alternatives you've considered**
> > Copy .thoth.yaml file into nested directories so that the configuration is picked along with the lock file.
> 
> What if different steps in a pipeline requires use of different hardware (just to mention one degree of freedom for the selection of the software stack)? each software stack should be coupled with a specific .thoth.yaml. See links above.

Adviser's input require direct dependencies, runtime environment and other vectors being constant. The resolved stack is specific to the input vector provided.

**Comment by fridex** [comment]
This can be closed as we introduced overlays. The overlay approach taken can manage multiple lock files for different runtime environments. See [overlays configuration option](https://github.com/thoth-station/thamos#overlays-directory).
