### ISSUE TITLE
Do not wait for the whole workflow to finish but use computed results ASAP

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#469]
**Describe the bug**

When running `thamos advise` I spotted that the client is waiting for the whole workflow to finish to obtain results. This is not nice as there are multiple tasks following the actual adviser task that computes results for the user. This makes responses from Thoth undesirable too long, we could obtain results as soon as they are available.

**To Reproduce**
1. Perform `thamos advise`
2. Go to OpenShift console
3. Observe adviser task is finished but the workflow is still running (e.g. graph sync task)
4. Client waits for the whole workflow to finish even though results of advise request are available on Ceph

**Expected behavior**

Results are obtained immediately as they are available.

**Additional context**

This does not require any changes on the backend itself. We could just switch the function that checks for results. Instead of using the status endpoint directly, we can pull results from the results endpoint which returns appropriate HTTP status code if the results are not available yet (otherwise results).

https://github.com/thoth-station/thamos/blob/672000a6b5a5337d4495ea5879c32cded527b3d6/thamos/lib.py#L96-L97

**Comment by saisankargochhayat** [comment]
The results endpoint refers to - `/advise/python/{analysis_id}` right?

**Comment by fridex** [comment]
> The results endpoint refers to - `/advise/python/{analysis_id}` right?

Yes.

**Comment by saisankargochhayat** [comment]
Closed with #475
