### ISSUE TITLE
Pre-Commit Test failed on autogenerated code

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#540]
> Pre-Commit Test failed! Click here

We should exclude the autogenerated code from checks.

_Originally posted by @fridex in https://github.com/thoth-station/thamos/pull/539#issuecomment-698913019_

**Comment by flowersw** [comment]
Is this just a matter of adding something like `exclude: "^(thamos/swagger_client/|examples/|docs/)"` at the top level in https://github.com/thoth-station/thamos/blob/master/.pre-commit-config.yaml , per https://pre-commit.com/#pre-commit-configyaml---top-level , or is it more complicated than that?

I also noticed that some of the pre-commit-hooks are repeated, and wasn't sure why

**Comment by fridex** [comment]
> Is this just a matter of adding something like `exclude: "^(thamos/swagger_client/|examples/|docs/)"` at the top level in https://github.com/thoth-station/thamos/blob/master/.pre-commit-config.yaml , per https://pre-commit.com/#pre-commit-configyaml---top-level , or is it more complicated than that?

Yes, I think your solution should do the trick :+1: 

> I also noticed that some of the pre-commit-hooks are repeated, and wasn't sure why

Most probably som copy-paste issue. I don't think it is required. Nice catch!

**Comment by flowersw** [comment]
Cool. I'll try and get a PR up soon. There's some trickiness around exclusions and mypy - see https://github.com/pre-commit/mirrors-mypy/issues/1 , but, we should be able to at least improve what is there

**Comment by fridex** [comment]
Awesome, thanks for looking into this! :+1:

**Comment by flowersw** [comment]
I think this can be closed, right?

**Comment by fridex** [comment]
> I think this can be closed, right?

Yes, thanks for the contribution.
