### ISSUE TITLE
Detect MKL version and send it to backend for MKL specific recommendations

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#578]
**Is your feature request related to a problem? Please describe.**

I, as Thoth user, would like to let thamos detect my MKL version installed on the system and send this information to Thoth's backend so that I get recommendations specific for my environment with MKL.

This way we can recommend using intel-tensorflow, instead of tensorflow if the environment has proper Intel MKL setup. Otherwise recommending intel-tensorflow can have negative performance impact (it requires MKL perf degrades significantly otherwise).

**Describe the solution you'd like**

Detect MKL version, similarly as in case of CUDA, and send this information to Thoth's backend. The recommendation engine can do its best to recommend libraries that work with my MKL setup.

**Required bits**

- [ ] detect MKL version on thamos side
- [ ] adjust schema on user-api so that user-api accepts MKL version, similarly as in case of CUDA
- [ ] extend adviser's runtime environment configuration so that it captures MKL version
- [ ] adjust pipeline units that recommend intel-tensorflow only if MKL version is setup in the given runtime environment
- [ ] capture differences across MKL versions and provide pipeline units that extend Thoth's knowledge base and can recommend releases specific for MKL version installed

**Comment by fridex** [comment]
Did a very brief check on this - I haven't found any direct way on how to get MKL version (as the lib can be basically placed anywhere on fs).

**Comment by goern** [comment]
cant we have a tiny c program that dynamically loads the library and get the version info? see https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-c/top/support-functions/version-information/mkl-get-version-string.html

**Comment by fridex** [comment]
We already have MKL configuration in the config file. Closing as already implemented.

/close
