### ISSUE TITLE
Duplicate entries in sources in Pipfile.lock

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#615]
**Describe the bug**

From time to time, I see duplicate source configuration in the recommended `Pipfile.lock`.

**To Reproduce**
1. Go to an application which has Thoth configured
2. Issue `thamos advise`
3. Check `Pipfile.lock` recommended by Thoth
4. See duplicate entries of source

An example project can be adviser.

**Expected behavior**

Only one source should be used (uniquely).

**Comment by fridex** [comment]
I see duplicate source configuration also in Pipfile.

**Comment by fridex** [comment]
The linked PR is not bugfix for this issue.

**Comment by fridex** [comment]
Was not able to reproduce it. IIRC it was using the adviser stack. I'll keep this open until we find a reproducer.

**Comment by fridex** [comment]
Moreover, this does not produce any issues when it comes to functionality and usability.

**Comment by goern** [comment]
@fridex is it save to close this?

**Comment by fridex** [comment]
I do not remember fixing this. And forgot to add reproducer, cannot spot this issue with a sample stack. I would say let's keep it and see if the issue arises again. It has no functionality drawback, it's just a cosmetic bug.

**Comment by goern** [comment]
@fridex as this is still open, can you work on it?

/priority backlog

**Comment by fridex** [comment]
Yes, it can be fixed. I would consider this low priority - it does not affect functionality anyhow. It's just there are more entries than expected.
