### ISSUE TITLE
Extend advise_here parameters inputs without using default local files.

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#622]
**Is your feature request related to a problem? Please describe.**
As part of new thoth integration for Jupyterlab (jupyterlab-requirements [1]) we want to submit advise directly using a method because metadata of a notebook can contain (pipfile, pipfile_lock and thoth config), without letting the method import all files input for the actual advise request to user-api from local path. 

Moreover, when will have the option to manipulate config input (recommendation type) directly from UI we can pass them directly to the method to ask advise.

**Describe the solution you'd like**
Extend advise_here method with `pipfile`, `pipfile_lock` and `config` that can be provided as parameters.

**Describe alternatives you've considered**
Store locally Pipfile and config modified by the user before asking for advise or creating pipfile.lock

**Additional context**
- [1] https://github.com/thoth-station/jupyterlab-requirements

**Comment by fridex** [comment]
> **Describe the solution you'd like**
> Extend advise_here method with `pipfile`, `pipfile_lock` and `config` that can be provided as parameters.

It looks to me that `advise` [1] method will be more suitable for this case (as you can pass directly Pipfile and Pipfile.lock). The issue I see is the config which is not parsed by a library function as of now. That would simplify config handling also in other parts of the project (like workflows when submitting request for a repo). I think this change corresponds to https://github.com/thoth-station/thamos/issues/384 (IMHO should not be closed). In that case, a method for parsing config should be introduced in the lib the parsed config should be passed to the advise method.

[1]: https://github.com/thoth-station/thamos/blob/f3c6472900acd0466c8c0133ee9838a8d0f7db21/thamos/lib.py#L303

**Comment by pacospace** [comment]
> > **Describe the solution you'd like**
> > Extend advise_here method with `pipfile`, `pipfile_lock` and `config` that can be provided as parameters.
> 
> It looks to me that `advise` [1](https://github.com/thoth-station/thamos/blob/f3c6472900acd0466c8c0133ee9838a8d0f7db21/thamos/lib.py#L303) method will be more suitable for this case (as you can pass directly Pipfile and Pipfile.lock). The issue I see is the config which is not parsed by a library function as of now. That would simplify config handling also in other parts of the project (like workflows when submitting request for a repo). I think this change corresponds to #384 (IMHO should not be closed). In that case, a method for parsing config should be introduced in the lib the parsed config should be passed to the advise method.

Thanks Frido now I get what you mean, I will reopen the other issue then and we can discuss some details next week :beers:

**Comment by fridex** [comment]
> > > **Describe the solution you'd like**
> > > Extend advise_here method with `pipfile`, `pipfile_lock` and `config` that can be provided as parameters.
> > 
> > 
> > It looks to me that `advise` [1](https://github.com/thoth-station/thamos/blob/f3c6472900acd0466c8c0133ee9838a8d0f7db21/thamos/lib.py#L303) method will be more suitable for this case (as you can pass directly Pipfile and Pipfile.lock). The issue I see is the config which is not parsed by a library function as of now. That would simplify config handling also in other parts of the project (like workflows when submitting request for a repo). I think this change corresponds to #384 (IMHO should not be closed). In that case, a method for parsing config should be introduced in the lib the parsed config should be passed to the advise method.
> 
> Thanks Frido now I get what you mean, I will reopen the other issue then and we can discuss some details next week

Opened #623 with an example. PTAL and let me know if you want to discuss details.

**Comment by pacospace** [comment]
> > > > **Describe the solution you'd like**
> > > > Extend advise_here method with `pipfile`, `pipfile_lock` and `config` that can be provided as parameters.
> > > 
> > > 
> > > It looks to me that `advise` [1](https://github.com/thoth-station/thamos/blob/f3c6472900acd0466c8c0133ee9838a8d0f7db21/thamos/lib.py#L303) method will be more suitable for this case (as you can pass directly Pipfile and Pipfile.lock). The issue I see is the config which is not parsed by a library function as of now. That would simplify config handling also in other parts of the project (like workflows when submitting request for a repo). I think this change corresponds to #384 (IMHO should not be closed). In that case, a method for parsing config should be introduced in the lib the parsed config should be passed to the advise method.
> > 
> > 
> > Thanks Frido now I get what you mean, I will reopen the other issue then and we can discuss some details next week
> 
> Opened #623 with an example. PTAL and let me know if you want to discuss details.

It is exactly what I was looking for, thanks @fridex !
