### ISSUE TITLE
Extend the configuration file with additional configuration options that are suitable for the recommendation engine

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#656]
**Is your feature request related to a problem? Please describe.**

Consider extending the configuration file so that it captures also additional options that can give better suited recommendations.

**Describe the solution you'd like**

Add more configuration options to the configuration file, such as cudnn version (besides cuda version) and such.

*Configuration to be included*

- [x] operating system and its version
- [x] available CPU model
- [x] cuda version
- [x] python version
- [x] cudnn version
- [x] GPU model
- [x] mkl version
- [x] nvidia driver version
- [x] openblas
- [x] openmpi
- [x] base image

**Comment by fridex** [comment]
CC @sub-mod do you have some input to this? Basically, we are extending versions of libraries that could be taken into account (outside of Python modules) when running tensorflow or other similar ML libraries.

**Comment by sub-mod** [comment]
- nvidia driver version
- gcc version
- openblas
- openmpi

**Comment by fridex** [comment]
> * nvidia driver version
> * gcc version
> * openblas
> * openmpi

Thanks, @sub-mod! Are all these specific to build time as well as to run time? Specifically, I'm curious about gcc version - is it needed during runtime once everything is built and installed from wheel files?

**Comment by fridex** [comment]
> * [ ]  base image

Adding also base image, CC @harshad16
