### ISSUE TITLE
Thamos advise has problem with local packages

### ISSUE THREAD

**Issue by tumido** [thoth-station/thamos#728]
**Describe the bug**
When there's a local package (specified via path/editable), `thamos advise` fails with `KeyError: 'version'`

**To Reproduce**
1. Have a `setup.py`:
```python
from setuptools import find_packages, setup

__version__ = "0.1.0"

setup(
    name="src",
    packages=find_packages(),
    version=__version__,
    license="",
)
```
2. Run `pipenv install -e .`
3. Verify you have a folder with:
- `setup.py` - see above
- `Pipfile`
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
src = {editable = true, path = "."}

[dev-packages]

[requires]
python_version = "3.6"
```
- `Pipfile.lock`
```json
{
    "_meta": {
        "hash": {
            "sha256": "93412bbf514cda8071435c5bca385ff4662a35ee453c08968d125ecfed56cbe9"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "src": {
            "editable": true,
            "path": "."
        }
    },
    "develop": {}
}
```
- `.thoth.yaml`
```
host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv

runtime_environments:
  - name: rhel:8
    operating_system:
      name: rhel
      version: "8"
    python_version: "3.8"
    recommendation_type: latest

```

4. Run `thamos advise`
```
2021-02-08 15:09:33,720 [51992] WARNING  thamos: Development dependencies will not be considered during the resolution process - see https://thoth-station.ninja/j/no_dev
2021-02-08 15:09:33,720 [51992] INFO     thamos.lib: Using Pipenv files located in the project root directory
2021-02-08 15:09:33,720 [51992] INFO     thamos.lib: Submitting Pipfile.lock as a base for user's stack scoring - see https://thoth-station.ninja/j/user_stack
2021-02-08 15:09:33,721 [51992] CRITICAL root: Traceback (most recent call last):
  File "/home/tcoufal/.local/bin/thamos", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tcoufal/.local/lib/python3.9/site-packages/thamos/cli.py", line 501, in advise
    results = thoth_advise_here(
  File "/home/tcoufal/.local/lib/python3.9/site-packages/thamos/lib.py", line 533, in advise_here
    project = Project.from_files(
  File "/home/tcoufal/.local/lib/python3.9/site-packages/thoth/python/project.py", line 86, in from_files
    pipfile = Pipfile.from_string(pipfile_str)
  File "/home/tcoufal/.local/lib/python3.9/site-packages/thoth/python/pipfile.py", line 331, in from_string
    return cls.from_dict(parsed)
  File "/home/tcoufal/.local/lib/python3.9/site-packages/thoth/python/pipfile.py", line 343, in from_dict
    packages=Packages.from_pipfile(packages, develop=False, meta=meta),
  File "/home/tcoufal/.local/lib/python3.9/site-packages/thoth/python/packages.py", line 89, in from_pipfile
    package_version[package_name] = PackageVersion.from_pipfile_entry(package_name, package_info, develop, meta)
  File "/home/tcoufal/.local/lib/python3.9/site-packages/thoth/python/package_version.py", line 313, in from_pipfile_entry
    package_version = entry.pop("version")
KeyError: 'version'
```

**Expected behavior**
It doesn't fail.

**Screenshots**
n/a

**Additional context**
https://github.com/operate-first/support/issues/68

**Comment by fridex** [comment]
Thanks for the report, Tomas. :+1: 

> **Expected behavior**
> It doesn't fail.

Sadly, we cannot recommend in this case. The application stack is not known to us hence we cannot give recommendations.

> **Describe the bug**
> When there's a local package (specified via path/editable), `thamos advise` fails with `KeyError: 'version'`

We should make sure this case is handled properly. Thamos should report the stack is using packages that are editables.

**Comment by tumido** [comment]
Hm.. We would like to get the recommendations even in case of local packages.. :/ What would it take to support that use case? Our problem is that `pipenv lock` generates a huge cache, which pollutes the user PVC...
 
Even if the package is just local and not editable (e.g.  `src = {path = "."}`) thamos fails to advise. 

The only workaroud on our end, I can think of, is to keep all the `src` dependencies in both the `setup.py` and `Pipfile`, remove `src` from `Pipfile` and use `sys.path.append` in all the local content which uses that local package... Can you think of any other/better solution?

**Comment by fridex** [comment]
> Hm.. We would like to get the recommendations even in case of local packages.. :/ What would it take to support that use case? Our problem is that `pipenv lock` generates a huge cache, which pollutes the user PVC...
> 
> Even if the package is just local and not editable (e.g. `src = {path = "."}`) thamos fails to advise.
> 
> The only workaroud on our end, I can think of, is to keep all the `src` dependencies in both the `setup.py` and `Pipfile`, remove `src` from `Pipfile` and use `sys.path.append` in all the local content which uses that local package... Can you think of any other/better solution?

The main issue here is that local files can have any patches or adjusted dependencies - we cannot perform any reliable recommendations or guidenance on the project. Relying on local files that are not available on any publicly consumable Python index (which would allow us to analyze dependencies) is a bad practice for us. Even the `PYTHONPATH` hack will introduce undesired results in many cases.

The insufficient PVC size issue linked is something Pipenv introduces - it bloats local cache directory (starting some specific Pipenv version). To bypass that issue, you can try to start using Thoth instead of Pipenv or fix https://github.com/pypa/pipenv/issues/3655 issue upstream. You can keep maintaining Pipfile and have `thamos advise` with `recommendation_type` set to latest, which mimics `pipenv lock` behavior. A subsequent `thamos install` will install dependencies (mimics `pipenv install`). You can combine both using `thamos advise --install`. In the worst case, increase the PVC size, but I guess we want to integrate anyway :) (CC @MichaelClifford)

Could you post exact set of packages that you want to have in the stack? We can have a look at them, if they need proper release management or something like that.

**Comment by fridex** [comment]
As local packages is something we will not support, I'm closing this one. Feel free to reopen if the issue persists.
