### ISSUE TITLE
Manage Pipenv files

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#745]
**Is your feature request related to a problem? Please describe.**

As per discussion with @pacospace in https://github.com/thoth-station/thamos/pull/744, we could add the capability to manage Pipenv files in Thamos. This way user could:

- [x] `thamos init` to initialize a project based on the configuration file (respecting overlays, ...) - not needed with `thamos config`
- [x] possibly other methods for adding new packages to Pipenv files, such as

  - [x] `thamos add <pkg> [--dev]` for adding a package to Pipfile - implemented
  - [x] `thamos install <pkg> [--dev]` for adding a package to Pipfile, triggering an advise and installing the stack
  - [ ] `thamos merge-overlays <o1> <o2> ... [--dev]` to merge a set of overlay directories into a new `Pipfile`

**Comment by pacospace** [comment]
@fridex do you think we can merge this request as well with new features in thamos? https://github.com/thoth-station/jupyterlab-requirements/issues/17#issuecomment-779296356

**Comment by fridex** [comment]
> @fridex do you think we can merge this request as well with new features in thamos? [thoth-station/jupyterlab-requirements#17 (comment)](https://github.com/thoth-station/jupyterlab-requirements/issues/17#issuecomment-779296356)

Yes, I think so. Ideally this logic should land in thoth-python where Pipfile abstraction covers all the Pipfile handling. :+1:

**Comment by pacospace** [comment]
> > @fridex do you think we can merge this request as well with new features in thamos? [thoth-station/jupyterlab-requirements#17 (comment)](https://github.com/thoth-station/jupyterlab-requirements/issues/17#issuecomment-779296356)
> 
> Yes, I think so. Ideally this logic should land in thoth-python where Pipfile abstraction covers all the Pipfile handling.

Sounds great, we can set a call to discuss details and new issues to work on. WDYT? what priority we want to give it @fridex @goern ?

**Comment by fridex** [comment]
Closing as this is already implemented - see `thamos add` `thamos remove` commands.
