### ISSUE TITLE
is thamos supposed to discover cuda info?

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#829]
**Describe the bug**

**To Reproduce**
1. `podman run -p 8888:8888 anupkumar/docker-ml-jupyterlab:galaxy-integration  jupyter lab --debug --allow-root` (the imag is ~15GB)

**Expected behavior**
Thamos should discover cuda and cunn version

**Screenshots**
![Screenshot from 2021-03-29 13-51-47](https://user-images.githubusercontent.com/27498679/112832713-01863980-9096-11eb-8085-dcbafe786b3b.png)

**Additional context**
Image DockerFile: https://github.com/anuprulez/ml-jupyter-notebook/blob/galaxy-inte-docker-ml-jupyter/Dockerfile

Testing jupyterlab-requirements issue with upstream user: https://github.com/thoth-station/jupyterlab-requirements/issues/233

**Comment by fridex** [comment]
Yes, it should:

https://github.com/thoth-station/thamos/blob/178af7ce9b638ea79bfe709da4ae99d7270de9e4/thamos/discover.py#L36-L37

Note there are some configuration options (like MKL) that are not currently part of the auto-discovery.

**Comment by pacospace** [comment]
> Yes, it should:
> 
> https://github.com/thoth-station/thamos/blob/178af7ce9b638ea79bfe709da4ae99d7270de9e4/thamos/discover.py#L36-L37
> 
> Note there are some configuration options (like MKL) that are not currently part of the auto-discovery.

Thanks @fridex, I linked the image with dockerfile above so we can use for some tests maybe.
