### ISSUE TITLE
write end of command to log

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#852]
**Is your feature request related to a problem? Please describe.**
It seems that the end of a command, like `advise`, just outputs to stdout, but not to log. It would be handy, for example to see the total execution time, or to have the command end in a structured form.

**Describe the solution you'd like**
log end of execution to log

**Describe alternatives you've considered**
n/a

**Additional context**
```
$thamos advise --force
/home/goern/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2021-05-01 21:13:15,254 [147654] WARNING  thamos: Development dependencies will not be considered during the resolution process - see https://thoth-station.ninja/j/no_dev
[...]
🕓  Waiting for response from Thoth (analysis: adviser-210501191316-7670222038090359)...
Resolver was killed as allocated CPU time was exceeded - https://thoth-station.ninja/j/cpu_time_exceeded
$
```

/kind feature

**Comment by fridex** [comment]
What is the use case of this?

BTW some timing can be seen when using `thamos --verbose advise`.
