### ISSUE TITLE
Cannot see content of config creted from string, content attribute reports None

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#898]
**Describe the bug**
Cannot see content of config creted from string, content attribute reports None

**To Reproduce**
```
        thoth_config_string = notebook_metadata.get('thoth_config')

        config = _Configuration()
        print(thoth_config_string)
        print(type(thoth_config_string))
        thoth_config_ = config.load_config_from_string(
            thoth_config_string
        )
        print(thoth_config_.content)
```
NOTE: Using `config.save_config()` correctly save to disc the loaded config.

**Expected behavior**
Thoth config is correctly created.

**Screenshots**
From code run above:

```
{"host":"khemenu.thoth-station.ninja","tls_verify":true,"requirements_format":"pipenv","overlays_dir":"overlays","virtualenv":false,"runtime_environments":[{"name":"demo-test1","operating_system":{"name":"fedora","version":"32"},"hardware":{"cpu_family":6,"cpu_model":142,"gpu_model":null},"python_version":"3.8","cuda_version":null,"recommendation_type":"latest","platform":"linux-x86_64","openblas_version":null,"openmpi_version":null,"cudnn_version":null,"mkl_version":null,"base_image":null}],"managers":[{"name":"pipfile-requirements"},{"name":"info"},{"name":"version","configuration":{"maintainers":[],"assignees":[],"labels":["bot"],"changelog_file":true,"changelog_smart":true}},{"name":"update","configuration":{"labels":["bot"]}}]}

<class 'str'>

Traceback (most recent call last):
  File "jupyterlab-requirements-cli", line 248, in <module>
    __name__ == "__main__" and cli()
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/fmurdaca/.local/share/virtualenvs/jupyterlab-requirements-wZBGhmnk/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "jupyterlab-requirements-cli", line 228, in notebook
    print(thoth_config_.content)
AttributeError: 'NoneType' object has no attribute 'content'
```

**Additional context**
Related-To: https://github.com/thoth-station/jupyterlab-requirements/issues/324

**Comment by fridex** [comment]
`load_config_from_string` method does not return anything, it loads the content to the private instance attribute.

See https://github.com/thoth-station/thamos/blob/6ab528338a71b0aa9311d2aab2d8b1f8b3e6771e/thamos/config.py#L248-L254

**Comment by pacospace** [comment]
> `load_config_from_string` method does not return anything, it loads the content to the private instance attribute.
> 
> See
> 
> https://github.com/thoth-station/thamos/blob/6ab528338a71b0aa9311d2aab2d8b1f8b3e6771e/thamos/config.py#L248-L254

Yes but once in self._configuration, running config.content, should give back the content:

```
    @property
    def content(self):
        """Access configuration."""
        if not self._configuration:
            self.load_config()

        return self._configuration

```

and it is None, is this expected?

**Comment by fridex** [comment]
If a function does not return anything, the return value defaults to `None` in Python:

```python
def foo():
   pass

var = foo()  # var is None
```

That means in your code:

```python
        thoth_config_ = config.load_config_from_string(
            thoth_config_string
        )
        print(thoth_config_.content)
```

`thoth_config_` will always be None. Accessing None on the subsequent line raises the attribute error reported.

**Comment by pacospace** [comment]
> If a function does not return anything, the return value defaults to `None` in Python:
> 
> ```python
> def foo():
>    pass
> 
> var = foo()  # var is None
> ```
> 
> That means in your code:
> 
> ```python
>         thoth_config_ = config.load_config_from_string(
>             thoth_config_string
>         )
>         print(thoth_config_.content)
> ```
> 
> `thoth_config_` will always be None. Accessing None on the subsequent line raises the attribute error reported.

of course, I m using wrong variable, I should use `config`, sorry for confusion, need more coffee ☕ Thanks @fridex!
