### ISSUE TITLE
Provide `thamos envinfo` command (or similar)

### ISSUE THREAD

**Issue by fridex** [thoth-station/thamos#920]
**Is your feature request related to a problem? Please describe.**

As a developer or data scientist, I would like to get information about the containerized environment I'm running the application in. 

Related: https://github.com/thoth-station/core/issues/336

**Describe the solution you'd like**

Provide `thamos envinfo` command that will provide guidance to users with respect to the containerized environment. The command can talk to the user-api and obtain information related to the containerized environment (ex. known security issues in the environment).

EDIT: the functionality can be part of `thamos check`

**Comment by codificat** [comment]
/priority backlog
(but feel free to adjust if appropriate - with a brief explanation)
