### ISSUE TITLE
thamos add command not working, not able to save Pipfile updated

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#925]
**Describe the bug**
thamos add command not working, not able to save Pipfile updated

**To Reproduce**
1. Using [jupyterlab-requirements](https://github.com/thoth-station/jupyterlab-requirements.git) kernels are created in `.local/share/thoth/{kernel-name}`

**Expected behavior**

**Screenshots**
```
 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  ls -al
total 68
drwxr-xr-x. 10 fmurdaca fmurdaca 4096 Nov  3 11:05 .
drwxrwxr-x.  6 fmurdaca fmurdaca 4096 Oct 26 17:45 ..
drwxr-xr-x.  3 fmurdaca fmurdaca 4096 Oct 21 14:59 bin
drwxr-xr-x.  3 fmurdaca fmurdaca 4096 Oct 21 14:59 etc
-rw-r--r--.  1 fmurdaca fmurdaca   40 Oct 21 14:58 .gitignore
drwxr-xr-x.  3 fmurdaca fmurdaca 4096 Oct 21 14:58 lib
drwxr-xr-x.  3 fmurdaca fmurdaca 4096 Oct 21 14:58 lib64
drwxr-xr-x.  3 fmurdaca fmurdaca 4096 Nov  3 11:05 overlays
-rw-r--r--.  1 fmurdaca fmurdaca  238 Oct 21 14:58 Pipfile
-rw-r--r--.  1 fmurdaca fmurdaca 6516 Oct 21 14:59 Pipfile.lock
-rw-r--r--.  1 fmurdaca fmurdaca  204 Oct 21 14:58 pyvenv.cfg
drwxr-xr-x.  2 fmurdaca fmurdaca 4096 Oct 21 14:59 README
drwxr-xr-x.  2 fmurdaca fmurdaca 4096 Oct 21 14:59 requirements.txt
drwxr-xr-x.  6 fmurdaca fmurdaca 4096 Oct 21 14:59 share
-rw-r--r--.  1 fmurdaca fmurdaca   37 Oct 21 14:58 .thoth_last_analysis_id
-rw-r--r--.  1 fmurdaca fmurdaca  739 Oct 21 14:58 .thoth.yaml

 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  cat Pipfile     
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
pandas = "*"

[dev-packages]

[requires]
python_version = "3.8"

 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  thamos add boto3
2021-11-03 11:05:36,388 [251945] INFO     thamos: Adding 'boto3' to default requirements of runtime environment 'new-test'
2021-11-03 11:05:36,388 [251945] WARNING  thamos: Changes done might require triggering new advise to resolve dependencies
 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  
 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  ls
bin  etc  lib  lib64  overlays  Pipfile  Pipfile.lock  pyvenv.cfg  README  requirements.txt  share

 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  cat Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
pandas = "*"

[dev-packages]

[requires]
python_version = "3.8"
 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  thamos add boto3
2021-11-03 11:07:37,382 [252486] INFO     thamos: Adding 'boto3' to default requirements of runtime environment 'new-test'
2021-11-03 11:07:37,382 [252486] WARNING  thamos: Changes done might require triggering new advise to resolve dependencies

 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  cat Pipfile 
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
pandas = "*"

[dev-packages]

[requires]
python_version = "3.8"
```

**Additional context**

**Comment by fridex** [comment]
I cannot reproduce this:


```
$ cat .thoth.yaml
host: khemenu.thoth-station.ninja
tls_verify: false
requirements_format: pipenv
overlays_dir: test

runtime_environments:
  - name: new-test
    operating_system:
      name: ubi
      version: "8"
    python_version: "3.8"
    recommendation_type: latest
$ ls test/
ls: cannot access 'test/': No such file or directory
$ thamos add boto3
2021-11-04 20:20:18,169 [53934] INFO     thamos.config: Creating directory structure in '/home/fpokorny/git/thoth-station/thamos/test/new-test'
2021-11-04 20:20:18,174 [53934] INFO     thamos: Adding 'boto3' to default requirements of runtime environment 'new-test'
2021-11-04 20:20:18,174 [53934] WARNING  thamos: Changes done might require triggering new advise to resolve dependencies
$ ls test
new-test
$ ls test/new-test/Pipfile 
test/new-test/Pipfile
$ cat test/new-test/Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
boto3 = "*"

[dev-packages]

[requires]
python_version = "3.8"

[thoth]
disable_index_adjustment = false

[thoth.allow_prereleases]
$ thamos add thoth-common
2021-11-04 20:20:43,217 [54201] INFO     thamos: Adding 'thoth-common' to default requirements of runtime environment 'new-test'
2021-11-04 20:20:43,218 [54201] WARNING  thamos: Changes done might require triggering new advise to resolve dependencies
$ cat test/new-test/Pipfile                                    
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi-org-simple"

[packages]
boto3 = "*"
thoth-common = "*"

[dev-packages]

[requires]
python_version = "3.8"

[thoth]
disable_index_adjustment = false

[thoth.allow_prereleases]
```

It looks like addition works when the overlays directory does not exist, but also when it exists. What is the content of `.thoth.yaml`, where is it located, and where `overlays_dir` option points to? I've tested also with `overlays_dir` set to `null` and it looks like it works (current main branch).

**Comment by pacospace** [comment]
the folder with Pipfile is located at `.local/share/kernels/test/` folder

**Comment by fridex** [comment]
> the folder with Pipfile is located at `.local/share/kernels/test/` folder

Based on the logs, it looks like it is located at `~/.local/share/thoth/kernels/new-test`:

```
 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  cat Pipfile 
```

Where is `.thoth.yaml` file located?

**Comment by pacospace** [comment]
> > the folder with Pipfile is located at `.local/share/kernels/test/` folder
> 
> Based on the logs, it looks like it is located at `~/.local/share/thoth/kernels/new-test`:
> 
> ```
>  fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  cat Pipfile 
> ```
> 
> Where is `.thoth.yaml` file located?

it is also located in that folder.

**Comment by fridex** [comment]
Could you please post also the content of `.thoth.yaml`? That would help understanding how the environment is set up. There are also `requirements.txt` in `~/.local/share/thoth/kernels/new-test` - what is the requirements format set in `.thoth.yaml` file?

**Comment by pacospace** [comment]
> Could you please post also the content of `.thoth.yaml`? That would help understanding how the environment is set up. There are also `requirements.txt` in `~/.local/share/thoth/kernels/new-test` - what is the requirements format set in `.thoth.yaml` file?

.thoth.yaml:
```
host: khemenu.thoth-station.ninja
managers:
- name: pipfile-requirements
- name: info
- configuration:
    assignees: []
    changelog_file: true
    changelog_smart: true
    labels:
    - bot
    maintainers: []
  name: version
- configuration:
    labels:
    - bot
  name: update
overlays_dir: overlays
requirements_format: pipenv
runtime_environments:
- base_image: null
  cuda_version: null
  cudnn_version: null
  hardware:
    cpu_family: 6
    cpu_model: 142
    gpu_model: null
  mkl_version: null
  name: new-test
  openblas_version: null
  openmpi_version: null
  operating_system:
    name: ubi
    version: '8'
  platform: linux-x86_64
  python_version: '3.8'
  recommendation_type: latest
tls_verify: true
virtualenv: false

```

this is created with the virtualenv:
```
 ✘ fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test  cd requirements.txt 
 fmurdaca@pc-7  ~/.local/share/thoth/kernels/new-test/requirements.txt  cat requirements.txt 
dictdiffer
jinja2
kubernetes ~= 11.0
python-string-utils
ruamel.yaml >= 0.15
six
```

**Comment by fridex** [comment]
> .thoth.yaml:
> 
> ```
> host: khemenu.thoth-station.ninja
> ...
> overlays_dir: overlays
> requirements_format: pipenv
> runtime_environments:
> - ...
>
>   name: new-test
> ...
> ```

The `requirements_format` is set to `pipenv` so Pipenv files should be corectly used. `overlays_dir` points to `overlays`. Based on this configuration, the Pipfile and Pipfile.lock files located in `~/.local/share/thoth/kernels/new-test/overlays/new-test` should be used, not the project root Pipenv files. Could you please check if that's the case?

**Comment by pacospace** [comment]
> > .thoth.yaml:
> > ```
> > host: khemenu.thoth-station.ninja
> > ...
> > overlays_dir: overlays
> > requirements_format: pipenv
> > runtime_environments:
> > - ...
> > 
> >   name: new-test
> > ...
> > ```
> 
> The `requirements_format` is set to `pipenv` so Pipenv files should be corectly used. `overlays_dir` points to `overlays`. Based on this configuration, the Pipfile and Pipfile.lock files located in `~/.local/share/thoth/kernels/new-test/overlays/new-test` should be used, not the project root Pipenv files. Could you please check if that's the case?

removing `overlays_dir: overlays` solved the problem. The config file is created automatically with autodiscovery, so having https://github.com/thoth-station/thamos/blob/7623f6f67c7a47ee5efcde8749eaf95510f88b36/thamos/data/defaultThoth.yaml#L14 by default seems to cause the issue, because I'm not considering overlays in that case. Each `kernel` has its own .thoth.yaml

**Comment by fridex** [comment]
You can provide a template that is automatically expanded based on autodiscovery and adjust only `overlays_dir` for jupyterlab-requirements specific case - see [docs](https://github.com/thoth-station/thamos#using-custom-configuration-file-template).

Another solution could be to keep thoth configuration in `~/.local/share/thoth/kernels/.thoth.yaml` and have a configuration that maps kernels to runtime environments as stated in `.thoth.yaml`. This might be a more clean solution but I'm not following how you designed kernels to Thoth config mapping in jupyterlab-requirements. A custom template would be needed in this case as well.

**Comment by pacospace** [comment]
> You can provide a template that is automatically expanded based on autodiscovery and adjust only `overlays_dir` for jupyterlab-requirements specific case - see [docs](https://github.com/thoth-station/thamos#using-custom-configuration-file-template).
> 
> Another solution could be to keep thoth configuration in `~/.local/share/thoth/kernels/.thoth.yaml` and have a configuration that maps kernels to runtime environments as stated in `.thoth.yaml`. This might be a more clean solution but I'm not following how you designed kernels to Thoth config mapping in jupyterlab-requirements. A custom template would be needed in this case as well.

The problem is we have to save also the thoth config in the notebook and having overlays and other runtime environments specific to that notebook, not sure if make sense, that is why kernel is mapped to single .thoth.yaml

**Comment by fridex** [comment]
> > You can provide a template that is automatically expanded based on autodiscovery and adjust only `overlays_dir` for jupyterlab-requirements specific case - see [docs](https://github.com/thoth-station/thamos#using-custom-configuration-file-template).
> > Another solution could be to keep thoth configuration in `~/.local/share/thoth/kernels/.thoth.yaml` and have a configuration that maps kernels to runtime environments as stated in `.thoth.yaml`. This might be a more clean solution but I'm not following how you designed kernels to Thoth config mapping in jupyterlab-requirements. A custom template would be needed in this case as well.
> 
> The problem is we have to save also the thoth config in the notebook metadata and having overlays and other runtime environments not specific to that notebook kernel, not sure if make sense, that is why kernel is mapped to single .thoth.yaml

That sounds like a logic that can embed the content into the notebook metadata. The embed logic can pick which runtime environment to keep in the notebook metadata. Also, information about other runtime environments can be kept in the notebook metadata and additional information can point to which runtime environment was used for resolving dependencies (which might be better as it will keep information for all runtime environments configured and information on which runtime environment was used from all configured).

**Comment by codificat** [comment]
My understanding is that the remaining work here has moved to the two issues linked from the jupyterlab-requirements repo. Therefore,

/close

If this is incorrect and there is still an issue in thamos around this, please reopen and clarify, thanks.
