### ISSUE TITLE
add more information required in the issue template for bug

### ISSUE THREAD

**Issue by pacospace** [thoth-station/thamos#931]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
add more information required in the issue template for bug:

pipfile, pipfile.lock, thamos version, .thoth.yaml

**Describe alternatives you've considered**

**Additional context**

**Comment by codificat** [comment]
Related: an attempt to improve the default templates for bugs and features: https://github.com/thoth-station/template-project/pull/29

**Comment by codificat** [comment]
/remove-lifecycle rotten

Ideally, the way to address this would be to make sure all the expected information is reflected in https://github.com/thoth-station/.github/pull/3, and then remove the issue templates from this (and other) repo(s) to inherit the ones in the `.github` repo.

/unassign @pacospace 
/assign
